### ISSUE TITLE
Write ingredient name parser

### ISSUE THREAD

**Issue by armsnyder** [friendly-flame/cheese-whiz#26]
Write a function that takes a raw ingredient name string from the basic html parser #13 output and processes it to divide it into a name, descriptor, preparation, and prep descriptor.

**Comment by kmads** [comment]
Use Regex ("ed", "ly", patterned exceptions, etc)

**Comment by armsnyder** [comment]
Good thinking :dancers:

**Comment by kmads** [comment]
Trying out nltk POS (part of speech) tags

**Comment by nakfoury** [comment]
Changing input format a little bit.
