### ISSUE TITLE
Write common substitution parser

### ISSUE THREAD

**Issue by armsnyder** [friendly-flame/cheese-whiz#5]
In kb.py there's a function stub for __format_raw_sub(raw_food_in, raw_food_out)
Finish this function to make it return a complete CommonSubstitution object.

The input parameters are completely unparsed, meaning you will need to separate quantity and measurement information, as well as parse the raw_food_out string for commas, 'and's, and 'or's.

Write the quantity/measurement parser as a separate function. It will be useful elsewhere in the project.

**Comment by armsnyder** [comment]
Do #14 first

**Comment by armsnyder** [comment]
Given the amount of NLP'ing to do for this issue, which you may find to be unnecessary, it might make sense to wait for @Pantsworth to finish issue #7 so you have a better idea of the input format.

**Comment by nakfoury** [comment]
Da.

**Comment by armsnyder** [comment]
You have test cases to accommodate, sir. Also you are smart and handsome.

**Comment by nakfoury** [comment]
:unamused:
