### ISSUE TITLE
Make south_asian_style.txt

### ISSUE THREAD

**Issue by armsnyder** [friendly-flame/cheese-whiz#58]
Make text file for transforming ingredients to South Asian style.

Acceptable formats:
ing1 = ing2
ing1, ing2 = ing3, ing4
ing1 = ing1, ing2

**Comment by nakfoury** [comment]
In kb_data folder

**Comment by nakfoury** [comment]
KnowledgeBase.italian_style = []

**Comment by nakfoury** [comment]
KnowledgeBase.south_asian_style = []
