### ISSUE TITLE
Write to_vegetarian function

### ISSUE THREAD

**Issue by armsnyder** [friendly-flame/cheese-whiz#65]
Write to_vegetarian function to take Recipe input and output vegetarian Recipe.

Loop through ingredients, checking food group (look in enums.py) for no-no groups. If the ingredient is of a no-no-group, check for a substitution in kb.vegetarian_substitutions (not yet written). If no suitable substitution can be found, replace with a quantity of TVP of equal weight.

**Comment by nakfoury** [comment]
In transformations.py

**Comment by kmads** [comment]
Works unless the ingredient list contains a Nonetype object (from parser). Refraining from pushing until I can get around this issue.
